[workspace]
resolver = "2"
members = ["crates/rustpad-core", "crates/rustpad-gtk"]

[workspace.package]
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "A fast, recoverable text editor in the spirit of modern Notepad"
repository = "https://github.com/tsubaie/RustPad"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
