[workspace]
resolver = "2"
members = ["crates/rustxt-core", "crates/rustxt-gtk", "crates/rustxt-iced"]
default-members = ["crates/rustxt-iced"]

[workspace.package]
version = "0.4.1"
edition = "2021"
license = "MIT"
description = "A dead simple, recoverable plain text editor"
repository = "https://github.com/tsubaie/RusTXT"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[patch.crates-io]
iced_graphics = { path = "vendor/iced_graphics" }
iced_widget = { path = "vendor/iced_widget" }
